# Generated by Django 4.1.6 on 2023-05-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pharmacy',
        ),
    ]
