# Generated by Django 4.1.5 on 2023-06-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0004_alter_products_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
