# Generated by Django 4.1.5 on 2023-06-16 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0006_alter_register_name_alter_register_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
